### ISSUE TITLE
Генерация координат

### ISSUE THREAD

**Issue by denyszamiatin** [denyszamiatin/2048#4]
Написать фрагмент программного кода для генерации пары координат в диапазоне от 0 до 3 для новой цифры на игровом поле

**Comment by DreamsEvil** [comment]
как принять то?

**Comment by FrontlineFraulein** [comment]
Assign yourself справа?

**Comment by DreamsEvil** [comment]
нету тут принять, всё облазил уже
http://prntscr.com/ba6pmj

**Comment by FrontlineFraulein** [comment]
У меня это выглядит так:
http://prntscr.com/ba6rfx

**Comment by DreamsEvil** [comment]
у меня такого к сожалению нет. Спасибо :)
Ну я если что займу эту часть кода
